ALTER PROFILE DEFAULT LIMIT
  FAILED_LOGIN_ATTEMPTS	UNLIMITED
  PASSWORD_REUSE_MAX	UNLIMITED
  PASSWORD_REUSE_TIME	UNLIMITED
  PASSWORD_LIFE_TIME	UNLIMITED
  PASSWORD_GRACE_TIME	30
  PASSWORD_LOCK_TIME	1
;
 
